# Generated by Django 5.2.17 on 2026-09-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuspark_usuario', '0001_initial'),
        ('campuspark_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoentrada',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuspark_veiculo.veiculo'),
        ),
        migrations.AddField(
            model_name='historicosaida',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuspark_veiculo.veiculo'),
        ),
        migrations.AddField(
            model_name='operador',
            name='tipo_operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campuspark_usuario.tipooperador'),
        ),
    ]
