# Generated by Django 5.2.17 on 2026-09-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuspark_usuario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email_institucional',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
