# Generated by Django 5.2.17 on 2026-09-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DENTRO', 'Dentro do estacionamento'), ('FINALIZADO', 'Saída registrada'), ('NEGADO', 'Acesso negado')], default='DENTRO', max_length=10)),
            ],
        ),
    ]
