# Generated by Django 5.2.17 on 2026-09-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuspark_acesso', '0001_initial'),
        ('campuspark_usuario', '0001_initial'),
        ('campuspark_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campuspark_usuario.operador'),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='campuspark_veiculo.veiculo'),
        ),
        migrations.AddIndex(
            model_name='registroacesso',
            index=models.Index(fields=['veiculo', 'status'], name='campuspark__veiculo_e621e4_idx'),
        ),
    ]
