# Generated by Django 5.2.17 on 2026-09-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuspark_acesso', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEstacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_carro', models.PositiveIntegerField(default=0)),
                ('vagas_moto', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Estacionamento',
                'verbose_name_plural': 'Configuração do Estacionamento',
            },
        ),
    ]
