# Generated by Django 6.1 on 2026-10-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuspark_acesso', '0003_configuracaoestacionamento'),
        ('campuspark_usuario', '0004_merge_usuario_migrations'),
        ('campuspark_veiculo', '0005_alter_veiculo_tag_rfid_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AberturaCancela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual')], max_length=10)),
                ('sentido', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('placa_informada', models.CharField(blank=True, max_length=7)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aberturas_cancela', to='campuspark_usuario.operador')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aberturas', to='campuspark_acesso.registroacesso')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aberturas_cancela', to='campuspark_veiculo.veiculo')),
            ],
            options={
                'verbose_name': 'Abertura da cancela',
                'verbose_name_plural': 'Aberturas da cancela',
                'ordering': ['-data_hora'],
            },
        ),
    ]
