# Generated by Django 5.2.17 on 2026-09-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuspark_usuario', '0003_seed_tipo_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='Vetor numérico (float32) que representa o rosto, gerado pelo modelo SFace.')),
                ('modelo_ia', models.CharField(default='sface_2021dec', help_text='Identifica qual modelo gerou o embedding, para não misturar vetores incompatíveis.', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrias', to='campuspark_usuario.aluno')),
            ],
            options={
                'indexes': [models.Index(fields=['aluno', 'ativo'], name='campuspark__aluno_i_c7c7c3_idx')],
            },
        ),
    ]
