# Generated by Django 5.2.17 on 2026-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='Vetor numérico (float32) que representa o rosto, gerado pelo modelo SFace.')),
                ('modelo_ia', models.CharField(default='sface_2021dec', help_text='Identifica qual modelo gerou o embedding, para não misturar vetores incompatíveis.', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
