# Generated by Django 5.2.17 on 2026-09-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuspark_biometria', '0001_initial'),
        ('campuspark_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometria',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrias', to='campuspark_usuario.aluno'),
        ),
        migrations.AddIndex(
            model_name='biometria',
            index=models.Index(fields=['aluno', 'ativo'], name='campuspark__aluno_i_c7c7c3_idx'),
        ),
    ]
