# Generated by Django 5.2.17 on 2026-09-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuspark_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuspark_usuario.aluno')),
            ],
        ),
    ]
