# Generated by Django 5.2.17 on 2026-09-20 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuspark_usuario', '0002_initial'),
        ('campuspark_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='fabricante',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tag_rfid',
            field=models.CharField(default='carro', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('outro', 'Outro')], default='PENDENTE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='campuspark_usuario.aluno'),
        ),
    ]
