# Generated by Django 5.2.17 on 2026-09-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuspark_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='modelo_ano',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='seguro_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(choices=[('AUTOMOVEL', 'Automóvel'), ('MOTOCICLETA', 'Motocicleta')], default='AUTOMOVEL', max_length=11),
        ),
    ]
